package com.yash;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.net.*;
import java.util.Arrays;
import java.util.logging.*;

/**
 *
 * @author Yash
 */
public class Home extends JFrame {

    Container c;
    CardLayout card;
    JPanel loginPagePanel = new JPanel();
    JPanel patientDetailsPagePanel = new JPanel();

    // Variables for NewPatient Data
    String nameTextField_Data, contactNumberTextField_Data, ageTextField_Data, genderButtonGroup_Data,
            bloodGroupList_Data, addressTextArea_Data, majorDiseaseTextArea_Data, patientID;

    // Variables for NewDiagnosis Data
    String patientIDTextField_Data, symptomsTextField_Data, diagnosisTextField_Data, medicinesTextField_Data,
            wardRequiredButtonGroup_Data;

    // Variables for Upadte Patient Data
    String updatePatientIDTextField_Data, updateNameTextField_Data, updateContactNumberTextField_Data,
            updateAgeTextField_Data, updateGenderButtonGroup_Data, updateBloodGroupList_Data,
            updateAddressTextArea_Data, updateMajorDiseaseTextArea_Data;

    /** Creates new form LoginForm */
    public Home() {

        LoginForm();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents

    void LoginForm() {

        c = getContentPane();
        card = new CardLayout();
        c.setLayout(card);
        c.add(loginPagePanel, BorderLayout.CENTER);
        c.add(patientDetailsPagePanel, BorderLayout.CENTER);

        JButton loginButton;
        JButton closeButton;
        JLabel uNameLabel;
        JLabel passLabel;
        JLabel loginPageLabel;
        JLabel errorLabel;
        JPasswordField passField;
        JTextField uNameTextField;

        uNameLabel = new JLabel();
        passLabel = new JLabel();
        loginPageLabel = new JLabel();
        errorLabel = new JLabel();
        uNameTextField = new JTextField();
        passField = new JPasswordField();
        loginButton = new JButton();
        closeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Detaile Mangement Sysytem");
        loginPagePanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        loginPagePanel.setMinimumSize(new Dimension(560, 500));
        loginPagePanel.setLayout(null);

        loginPageLabel.setFont(new Font("Poppins SemiBold", 1, 22)); // NOI18N
        loginPageLabel.setText("Login Page");
        loginPagePanel.add(loginPageLabel);
        loginPageLabel.setBounds(210, 20, 300, 28);

        uNameLabel.setFont(new Font("Poppins", 0, 12)); // NOI18N
        uNameLabel.setText("Username");
        loginPagePanel.add(uNameLabel);
        uNameLabel.setBounds(120, 105, 70, 19);

        passLabel.setFont(new Font("Poppins", 0, 12)); // NOI18N
        passLabel.setText("Password");
        loginPagePanel.add(passLabel);
        passLabel.setBounds(120, 145, 70, 19);

        loginPagePanel.add(uNameTextField);
        uNameTextField.setBounds(220, 100, 160, 27);
        loginPagePanel.add(passField);
        passField.setBounds(220, 140, 160, 27);

        errorLabel.setFont(new Font("Poppins", 0, 12)); // NOI18N
        errorLabel.setForeground(Color.RED);
        loginPagePanel.add(errorLabel);
        errorLabel.setBounds(120, 190, 300, 19);

        loginButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginPagePanel.add(loginButton);
        loginButton.setBounds(90, 250, 75, 26);

        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                String userName = uNameTextField.getText();
                char[] passwordChars = passField.getPassword();
                String pass = new String(passwordChars);
                String storedName = "@123";
                String storedPassword = "secret";
                if (storedName.equals(userName) && storedPassword.equals(pass)) {
                    card.next(c);
                } else
                    errorLabel.setText("Username or Password are incorrect please verify.");
            }
        });

        closeButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        closeButton.setText("Close");
        loginPagePanel.add(closeButton);
        closeButton.setBounds(350, 250, 72, 26);
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });

        patientDetailsPagePanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        patientDetailsPagePanel.setMinimumSize(new Dimension(560, 500));
        patientDetailsPagePanel.setLayout(new BorderLayout());

        JTabbedPane tabbedPane = new JTabbedPane(JTabbedPane.SCROLL_TAB_LAYOUT);

        JPanel newPatientRecordPanel = new JPanel(null);
        JPanel diagnosisInformationPanel = new JPanel(null);
        JPanel historyOfPatientPanel = new JPanel(null);
        JPanel updatePatientRecord = new JPanel(null);

        // Add New Patient Record
        JLabel patientNameLabel, contactNumberLabel, ageLabel, genderLabel, bloodGroupLabel, addressLabel,
                majorDiseaseLabel;
        JTextField nameTextField, contactNumberTextField, ageTextField;
        JTextArea addressTextArea, majorDiseaseTextArea;
        JButton newPatientRecord_SaveButton, newPatientRecord_CloseButton;
        ButtonGroup genderButtonGroup = new ButtonGroup();
        JRadioButton genderMaleRadioButton, genderFemaleRadioButton, genderOtherRadioButton, genderUnselectRadioButton;
        JComboBox bloodGroupList;
        Object[] bloodGroupObject = { "A+ve", "O+ve", "B+ve", "AB+ve", "A-ne", "O-ne", "B-ne", "AB-ne" };
        JScrollPane jsp;

        patientNameLabel = new JLabel("Patient Name");
        patientNameLabel.setFont(new Font("Poppins", 40, 12));
        patientNameLabel.setBounds(30, 13, 79, 19);
        newPatientRecordPanel.add(patientNameLabel);

        nameTextField = new JTextField();
        nameTextField.setFont(new Font("Poppins", 40, 12));
        nameTextField.setBounds(130, 10, 210, 26);
        newPatientRecordPanel.add(nameTextField);

        contactNumberLabel = new JLabel("Contact Number");
        contactNumberLabel.setFont(new Font("Poppins", 40, 12));
        contactNumberLabel.setBounds(30, 43, 150, 19);
        newPatientRecordPanel.add(contactNumberLabel);

        contactNumberTextField = new JTextField();
        contactNumberTextField.setFont(new Font("Poppins", 40, 12));
        contactNumberTextField.setBounds(130, 40, 210, 26);
        newPatientRecordPanel.add(contactNumberTextField);

        ageLabel = new JLabel("Age");
        ageLabel.setFont(new Font("Poppins", 40, 12));
        ageLabel.setBounds(30, 73, 150, 19);
        newPatientRecordPanel.add(ageLabel);

        ageTextField = new JTextField();
        ageTextField.setFont(new Font("Poppins", 40, 12));
        ageTextField.setBounds(130, 70, 210, 26);
        newPatientRecordPanel.add(ageTextField);

        genderLabel = new JLabel("Gender");
        genderLabel.setFont(new Font("Poppins", 40, 12));
        genderLabel.setBounds(30, 103, 70, 19);
        newPatientRecordPanel.add(genderLabel);

        genderMaleRadioButton = new JRadioButton("Male");
        genderMaleRadioButton.setFont(new Font("Poppins", 40, 12));
        genderMaleRadioButton.setBounds(130, 103, 65, 19);
        genderButtonGroup.add(genderMaleRadioButton);
        newPatientRecordPanel.add(genderMaleRadioButton);

        genderFemaleRadioButton = new JRadioButton("Female");
        genderFemaleRadioButton.setFont(new Font("Poppins", 40, 12));
        genderFemaleRadioButton.setBounds(200, 103, 75, 19);
        genderButtonGroup.add(genderFemaleRadioButton);
        newPatientRecordPanel.add(genderFemaleRadioButton);

        genderOtherRadioButton = new JRadioButton("Other");
        genderOtherRadioButton.setFont(new Font("Poppins", 40, 12));
        genderOtherRadioButton.setBounds(280, 103, 65, 19);
        genderButtonGroup.add(genderOtherRadioButton);
        newPatientRecordPanel.add(genderOtherRadioButton);
        genderUnselectRadioButton = new JRadioButton("Unselect");
        genderButtonGroup.add(genderUnselectRadioButton);

        bloodGroupLabel = new JLabel("Blood Group");
        bloodGroupLabel.setFont(new Font("Poppins", 40, 12));
        bloodGroupLabel.setBounds(30, 133, 120, 19);
        newPatientRecordPanel.add(bloodGroupLabel);

        bloodGroupList = new JComboBox(bloodGroupObject);
        bloodGroupList.setFont(new Font("Poppins", 40, 12));
        bloodGroupList.setBounds(130, 130, 65, 22);
        newPatientRecordPanel.add(bloodGroupList);

        addressLabel = new JLabel("Address");
        addressLabel.setFont(new Font("Poppins", 40, 12));
        addressLabel.setBounds(30, 163, 120, 19);
        newPatientRecordPanel.add(addressLabel);

        addressTextArea = new JTextArea();
        addressTextArea.setLineWrap(true);
        addressTextArea.setWrapStyleWord(true);
        addressTextArea.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(addressTextArea);
        jsp.setBounds(130, 160, 210, 90);
        newPatientRecordPanel.add(jsp);

        majorDiseaseLabel = new JLabel("Any Major Disease Suffered Earlier");
        majorDiseaseLabel.setFont(new Font("Poppins", 40, 12));
        majorDiseaseLabel.setBounds(30, 269, 300, 19);
        newPatientRecordPanel.add(majorDiseaseLabel);

        majorDiseaseTextArea = new JTextArea();
        majorDiseaseTextArea.setLineWrap(true);
        majorDiseaseTextArea.setWrapStyleWord(true);
        majorDiseaseTextArea.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(majorDiseaseTextArea);
        jsp.setBounds(130, 290, 221, 90);
        newPatientRecordPanel.add(jsp);

        newPatientRecord_SaveButton = new JButton("Save");
        newPatientRecord_SaveButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        newPatientRecord_SaveButton.setBounds(30, 380, 72, 26);
        newPatientRecordPanel.add(newPatientRecord_SaveButton);
        newPatientRecord_SaveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                nameTextField_Data = nameTextField.getText();
                contactNumberTextField_Data = contactNumberTextField.getText();
                ageTextField_Data = ageTextField.getText();
                if (genderMaleRadioButton.isSelected()) {
                    genderButtonGroup_Data = genderMaleRadioButton.getText();
                } else if (genderFemaleRadioButton.isSelected()) {
                    genderButtonGroup_Data = genderFemaleRadioButton.getText();
                } else if (genderOtherRadioButton.isSelected()) {
                    genderButtonGroup_Data = genderOtherRadioButton.getText();
                }
                bloodGroupList_Data = (String) bloodGroupList.getSelectedItem();
                addressTextArea_Data = addressTextArea.getText();
                majorDiseaseTextArea_Data = majorDiseaseTextArea.getText();
                try {
                    Socket soc = new Socket("192.168.137.1", 2001);
                    BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
                    PrintWriter out = new PrintWriter(soc.getOutputStream(), true);
                    out.println(nameTextField_Data);
                    out.println(contactNumberTextField_Data);
                    out.println(ageTextField_Data);
                    out.println(genderButtonGroup_Data);
                    out.println(bloodGroupList_Data);
                    out.println(addressTextArea_Data);
                    out.println(majorDiseaseTextArea_Data);
                    patientID = in.readLine();
                    System.out.println(patientID);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }

                JFrame patientIDFrame = new JFrame("Patient ID");
                JDialog patientIDDialog = new JDialog(patientIDFrame, "Patient ID");
                JLabel patientNameLabel = new JLabel("Patient Name:", 0);
                JTextField patientIDTextField = new JTextField(16);

                patientIDDialog.setLocationRelativeTo(null);
                patientIDDialog.setLayout(new GridLayout(2, 2));
                patientIDDialog.setSize(400, 100);
                patientIDDialog.setModal(true);

                patientIDTextField.setFont(new Font("Poppins", 0, 12));
                patientNameLabel.setFont(new Font("Poppins", 0, 12));
                patientIDTextField.setText(patientID);
                patientIDTextField.setEditable(false);
                patientNameLabel.setText(nameTextField.getText());
                patientIDDialog.add(new JLabel("Patient Name:", 0));
                patientIDDialog.add(patientNameLabel);
                patientIDDialog.add(new JLabel("\nPatient ID: ", 0));
                patientIDDialog.add(patientIDTextField);
                patientIDDialog.setVisible(true);
                nameTextField.setText("");
                contactNumberTextField.setText("");
                ageTextField.setText("");
                genderUnselectRadioButton.setSelected(true);
                addressTextArea.setText("");
                majorDiseaseTextArea.setText("");
                System.out.println("HELLO");
                patientIDFrame.add(patientIDDialog);
            }
        });

        newPatientRecord_CloseButton = new JButton("Close");
        newPatientRecord_CloseButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        newPatientRecord_CloseButton.setBounds(380, 380, 72, 26);
        newPatientRecordPanel.add(newPatientRecord_CloseButton);
        newPatientRecord_CloseButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });

        // New diagnosis Information
        JLabel patientIDLabel, symptomsLabel, diagnosisLabel, medicinesLabel, wardRequiredLabel;
        JTextField patientIDTextField, symptomsTextField, diagnosisTextField, medicinesTextField;
        JButton Diagnosis_searchButton, Diagnosis_saveButton, Diagnosis_closeButton;
        ButtonGroup wardRequiredButtonGroup = new ButtonGroup();
        JRadioButton wardRequiredYesRadioButton, wardRequiredNoRadioButton, wardReqiredUnselectedRadioButton;
        DefaultTableModel DiagnosisInformationDefaultTableModel;
        JTable patientTable;

        patientIDLabel = new JLabel("Patient ID");
        patientIDLabel.setFont(new Font("Poppins", 40, 12));
        patientIDLabel.setBounds(30, 13, 60, 19);
        diagnosisInformationPanel.add(patientIDLabel);

        patientIDTextField = new JTextField();
        patientIDTextField.setFont(new Font("Poppins", 40, 12));
        patientIDTextField.setBounds(100, 10, 127, 26);
        diagnosisInformationPanel.add(patientIDTextField);

        Diagnosis_searchButton = new JButton("Search");
        Diagnosis_searchButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        Diagnosis_searchButton.setBounds(250, 10, 72, 26);
        diagnosisInformationPanel.add(Diagnosis_searchButton);

        String[] columnNames = { "Patient ID", "Date", "Time", "Name", "Contact Number", "Age", "Gender",
                "Blood Group", " Address" };
        Object[][] data = {};

        DiagnosisInformationDefaultTableModel = new DefaultTableModel(data, columnNames);

        try {
            Socket soc = new Socket("192.168.137.1", 1984);
            BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
            PrintWriter out = new PrintWriter(soc.getOutputStream(), true);

            String line;
            while (!(line = in.readLine()).equals("null")) {
                System.out.println(line);
                String[] rowData = line.split("~");
                DiagnosisInformationDefaultTableModel.addRow(Arrays.copyOf(rowData, rowData.length));
                System.out.println(rowData.toString());

            }
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        Diagnosis_searchButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                String patientIDTextField_Data = patientIDTextField.getText();
                try {
                    Socket soc = new Socket("192.168.137.1", 2011);
                    BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
                    PrintWriter out = new PrintWriter(soc.getOutputStream(), true);

                    int i = DiagnosisInformationDefaultTableModel.getRowCount();
                    for (int j = 0; j < i; j++) {
                        DiagnosisInformationDefaultTableModel.removeRow(0);
                    }
                    System.out.println(patientIDTextField_Data);
                    out.println(patientIDTextField_Data);

                    String line;
                    while (!(line = in.readLine()).equals("null")) {
                        System.out.println(line);
                        String[] rowData = line.split("~");
                        DiagnosisInformationDefaultTableModel.addRow(Arrays.copyOf(rowData, rowData.length));
                        System.out.println(rowData.toString());
                    }

                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        patientTable = new JTable(DiagnosisInformationDefaultTableModel);

        for (int i = 0; i < patientTable.getColumnCount(); i++) {
            patientTable.setDefaultEditor(patientTable.getColumnClass(i), null);
        }
        patientTable.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(patientTable);
        jsp.setBounds(0, 70, 538, 100);
        diagnosisInformationPanel.add(jsp);

        symptomsLabel = new JLabel("Symptoms");
        symptomsLabel.setFont(new Font("Poppins", 40, 12));
        symptomsLabel.setBounds(10, 200, 80, 19);
        diagnosisInformationPanel.add(symptomsLabel);

        symptomsTextField = new JTextField();
        symptomsTextField.setFont(new Font("Poppins", 40, 12));
        symptomsTextField.setBounds(100, 198, 250, 26);
        diagnosisInformationPanel.add(symptomsTextField);

        diagnosisLabel = new JLabel("Diagnosis");
        diagnosisLabel.setFont(new Font("Poppins", 40, 12));
        diagnosisLabel.setBounds(10, 230, 80, 19);
        diagnosisInformationPanel.add(diagnosisLabel);

        diagnosisTextField = new JTextField();
        diagnosisTextField.setFont(new Font("Poppins", 40, 12));
        diagnosisTextField.setBounds(100, 228, 250, 26);
        diagnosisInformationPanel.add(diagnosisTextField);

        medicinesLabel = new JLabel("Medicines");
        medicinesLabel.setFont(new Font("Poppins", 40, 12));
        medicinesLabel.setBounds(10, 260, 80, 19);
        diagnosisInformationPanel.add(medicinesLabel);

        medicinesTextField = new JTextField();
        medicinesTextField.setFont(new Font("Poppins", 40, 12));
        medicinesTextField.setBounds(100, 258, 250, 26);
        diagnosisInformationPanel.add(medicinesTextField);

        wardRequiredLabel = new JLabel("Ward Required?");
        wardRequiredLabel.setFont(new Font("Poppins", 40, 12));
        wardRequiredLabel.setBounds(10, 300, 130, 19);
        diagnosisInformationPanel.add(wardRequiredLabel);

        wardRequiredYesRadioButton = new JRadioButton("Yes");
        wardRequiredYesRadioButton.setFont(new Font("Poppins", 40, 12));
        wardRequiredYesRadioButton.setBounds(120, 300, 50, 19);
        wardRequiredButtonGroup.add(wardRequiredYesRadioButton);
        diagnosisInformationPanel.add(wardRequiredYesRadioButton);

        wardRequiredNoRadioButton = new JRadioButton("No");
        wardRequiredNoRadioButton.setFont(new Font("Poppins", 40, 12));
        wardRequiredNoRadioButton.setBounds(180, 300, 50, 19);
        wardRequiredButtonGroup.add(wardRequiredNoRadioButton);
        wardReqiredUnselectedRadioButton = new JRadioButton("Unselect");
        wardRequiredButtonGroup.add(wardReqiredUnselectedRadioButton);
        diagnosisInformationPanel.add(wardRequiredNoRadioButton);

        Diagnosis_saveButton = new JButton("Save");
        Diagnosis_saveButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        Diagnosis_saveButton.setBounds(30, 350, 72, 26);
        diagnosisInformationPanel.add(Diagnosis_saveButton);
        Diagnosis_saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                patientIDTextField_Data = patientIDTextField.getText();
                symptomsTextField_Data = symptomsTextField.getText();
                diagnosisTextField_Data = diagnosisTextField.getText();
                medicinesTextField_Data = medicinesTextField.getText();
                if (wardRequiredYesRadioButton.isSelected()) {
                    wardRequiredButtonGroup_Data = wardRequiredYesRadioButton.getText();
                } else if (wardRequiredNoRadioButton.isSelected()) {
                    wardRequiredButtonGroup_Data = wardRequiredNoRadioButton.getText();
                }
                try {
                    Socket soc = new Socket("192.168.137.1", 1939);
                    BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
                    PrintWriter out = new PrintWriter(soc.getOutputStream(), true);
                    out.println(patientIDTextField_Data);
                    out.println(symptomsTextField_Data);
                    out.println(diagnosisTextField_Data);
                    out.println(medicinesTextField_Data);
                    out.println(wardRequiredButtonGroup_Data);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                wardReqiredUnselectedRadioButton.setSelected(true);
                patientIDTextField.setText("");
                symptomsTextField.setText("");
                diagnosisTextField.setText("");
                medicinesTextField.setText("");
            }
        });

        Diagnosis_closeButton = new JButton("Close");
        Diagnosis_closeButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        Diagnosis_closeButton.setBounds(380, 350, 72, 26);
        diagnosisInformationPanel.add(Diagnosis_closeButton);
        Diagnosis_closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });

        // Full Data of Patient
        DefaultTableModel historyOfPatientDefaultTableModel;
        JTable historyOfPatientTable;
        JButton historyOfPatient_CloseButton, historyOfPatient_RefreshButton;

        Object[] historyOfPatientColumnNames = { "Patient ID", "Date", "Time", "Name", "Contact Number", "Age",
                "Gender", "Blood Group", "Address", "Major Disease Suffered Earlier", "Symptoms", "Diagnosis",
                "Medicines",
                "Ward Required?" };
        Object[][] historyOfPatientData = {};

        historyOfPatientDefaultTableModel = new DefaultTableModel(historyOfPatientData, historyOfPatientColumnNames);
        try {
            Socket soc = new Socket("192.168.137.1", 2008);
            BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
            PrintWriter out = new PrintWriter(soc.getOutputStream(), true);
            String line;
            while (!(line = in.readLine()).equals("null")) {
                System.out.println(line);
                String[] rowData = line.split("~");
                historyOfPatientDefaultTableModel.addRow(Arrays.copyOf(rowData,
                        rowData.length));
                System.out.println(rowData.toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);

        }

        historyOfPatient_RefreshButton = new JButton("Refresh");
        historyOfPatient_RefreshButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        historyOfPatient_RefreshButton.setBounds(30, 350, 72, 26);
        historyOfPatientPanel.add(historyOfPatient_RefreshButton);
        historyOfPatient_RefreshButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                try {
                    Socket soc = new Socket("192.168.137.1", 1986);
                    BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
                    PrintWriter out = new PrintWriter(soc.getOutputStream(), true);
                    int i = historyOfPatientDefaultTableModel.getRowCount();
                    for (int j = 0; j < i; j++) {
                        historyOfPatientDefaultTableModel.removeRow(0);
                    }
                    String line;
                    while (!(line = in.readLine()).equals("null")) {
                        System.out.println(line);
                        String[] rowData = line.split("~");
                        historyOfPatientDefaultTableModel.addRow(Arrays.copyOf(rowData,
                                rowData.length));
                        System.out.println(rowData.toString());
                    }

                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        historyOfPatientTable = new JTable(historyOfPatientDefaultTableModel);

        for (int i = 0; i < historyOfPatientTable.getColumnCount(); i++) {
            historyOfPatientTable.setDefaultEditor(historyOfPatientTable.getColumnClass(i),
                    null);
        }
        historyOfPatientTable.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(historyOfPatientTable);
        jsp.setBounds(0, 10, 538, 300);
        historyOfPatientPanel.add(jsp);

        historyOfPatient_CloseButton = new JButton("Close");
        historyOfPatient_CloseButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        historyOfPatient_CloseButton.setBounds(380, 350, 72, 26);
        historyOfPatientPanel.add(historyOfPatient_CloseButton);
        historyOfPatient_CloseButton.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });

        // Update Patient Record
        JLabel updatePatientIDLabel, updatePatientNameLabel, updateContactNumberLabel, updateAgeLabel,
                updateGenderLabel,
                updateBloodGroupLabel, updateAddressLabel, updateMajorDiseaseLabel;
        JTextField updatePatientIDTextField, updateNameTextField, updateContactNumberTextField, updateAgeTextField;
        JTextArea updateAddressTextArea, updateMajorDiseaseTextArea;
        JButton updatePatientRecord_UpdateButton, updatePatientRecord_CloseButton;
        ButtonGroup updateGenderButtonGroup = new ButtonGroup();
        JRadioButton updateGenderMaleRadioButton, updateGenderFemaleRadioButton, updateGenderOtherRadioButton,
                updateGenderUnselectedRadioButton;
        JComboBox updateBloodGroupList;
        Object[] updateBloodGroupObject = { "A+ve", "O+ve", "B+ve", "AB+ve", "A-ve", "O-ve", "B-ve", "AB-ve" };

        updatePatientIDLabel = new JLabel("Patient ID");
        updatePatientIDLabel.setFont(new Font("Poppins", 40, 12));
        updatePatientIDLabel.setBounds(350, 13, 60, 19);
        updatePatientRecord.add(updatePatientIDLabel);

        updatePatientIDTextField = new JTextField();
        updatePatientIDTextField.setFont(new Font("Poppins", 40, 12));
        updatePatientIDTextField.setBounds(420, 10, 115, 26);
        updatePatientRecord.add(updatePatientIDTextField);

        updatePatientNameLabel = new JLabel("Patient Name");
        updatePatientNameLabel.setFont(new Font("Poppins", 40, 12));
        updatePatientNameLabel.setBounds(30, 13, 79, 19);
        updatePatientRecord.add(updatePatientNameLabel);

        updateNameTextField = new JTextField();
        updateNameTextField.setFont(new Font("Poppins", 40, 12));
        updateNameTextField.setBounds(130, 10, 210, 26);
        updatePatientRecord.add(updateNameTextField);

        updateContactNumberLabel = new JLabel("Contact Number");
        updateContactNumberLabel.setFont(new Font("Poppins", 40, 12));
        updateContactNumberLabel.setBounds(30, 43, 150, 19);
        updatePatientRecord.add(updateContactNumberLabel);

        updateContactNumberTextField = new JTextField();
        updateContactNumberTextField.setFont(new Font("Poppins", 40, 12));
        updateContactNumberTextField.setBounds(130, 40, 210, 26);
        updatePatientRecord.add(updateContactNumberTextField);

        updateAgeLabel = new JLabel("Age");
        updateAgeLabel.setFont(new Font("Poppins", 40, 12));
        updateAgeLabel.setBounds(30, 73, 150, 19);
        updatePatientRecord.add(updateAgeLabel);

        updateAgeTextField = new JTextField();
        updateAgeTextField.setFont(new Font("Poppins", 40, 12));
        updateAgeTextField.setBounds(130, 70, 210, 26);
        updatePatientRecord.add(updateAgeTextField);

        updateGenderLabel = new JLabel("Gender");
        updateGenderLabel.setFont(new Font("Poppins", 40, 12));
        updateGenderLabel.setBounds(30, 103, 70, 19);
        updatePatientRecord.add(updateGenderLabel);

        updateGenderMaleRadioButton = new JRadioButton("Male");
        updateGenderMaleRadioButton.setFont(new Font("Poppins", 40, 12));
        updateGenderMaleRadioButton.setBounds(130, 103, 65, 19);
        updateGenderButtonGroup.add(updateGenderMaleRadioButton);
        updatePatientRecord.add(updateGenderMaleRadioButton);

        updateGenderFemaleRadioButton = new JRadioButton("Female");
        updateGenderFemaleRadioButton.setFont(new Font("Poppins", 40, 12));
        updateGenderFemaleRadioButton.setBounds(200, 103, 75, 19);
        updateGenderButtonGroup.add(updateGenderFemaleRadioButton);
        updatePatientRecord.add(updateGenderFemaleRadioButton);

        updateGenderOtherRadioButton = new JRadioButton("Other");
        updateGenderOtherRadioButton.setFont(new Font("Poppins", 40, 12));
        updateGenderOtherRadioButton.setBounds(280, 103, 65, 19);
        updateGenderButtonGroup.add(updateGenderOtherRadioButton);
        updateGenderUnselectedRadioButton = new JRadioButton("Uselected");
        updateGenderButtonGroup.add(updateGenderUnselectedRadioButton);
        updatePatientRecord.add(updateGenderOtherRadioButton);

        updateBloodGroupLabel = new JLabel("Blood Group");
        updateBloodGroupLabel.setFont(new Font("Poppins", 40, 12));
        updateBloodGroupLabel.setBounds(30, 133, 120, 19);
        updatePatientRecord.add(updateBloodGroupLabel);

        updateBloodGroupList = new JComboBox(updateBloodGroupObject);
        updateBloodGroupList.setFont(new Font("Poppins", 40, 12));
        updateBloodGroupList.setBounds(130, 130, 65, 22);
        updatePatientRecord.add(updateBloodGroupList);

        updateAddressLabel = new JLabel("Address");
        updateAddressLabel.setFont(new Font("Poppins", 40, 12));
        updateAddressLabel.setBounds(30, 163, 120, 19);
        updatePatientRecord.add(updateAddressLabel);

        updateAddressTextArea = new JTextArea();
        updateAddressTextArea.setLineWrap(true);
        updateAddressTextArea.setWrapStyleWord(true);
        updateAddressTextArea.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(updateAddressTextArea);
        jsp.setBounds(130, 160, 210, 90);
        updatePatientRecord.add(jsp);

        updateMajorDiseaseLabel = new JLabel("Any Major Disease Suffered Earlier");
        updateMajorDiseaseLabel.setFont(new Font("Poppins", 40, 12));
        updateMajorDiseaseLabel.setBounds(30, 269, 300, 19);
        updatePatientRecord.add(updateMajorDiseaseLabel);

        updateMajorDiseaseTextArea = new JTextArea();
        updateMajorDiseaseTextArea.setLineWrap(true);
        updateMajorDiseaseTextArea.setWrapStyleWord(true);
        updateMajorDiseaseTextArea.setFont(new Font("Poppins", 40, 12));
        jsp = new JScrollPane(updateMajorDiseaseTextArea);
        jsp.setBounds(130, 290, 221, 90);
        updatePatientRecord.add(jsp);

        updatePatientRecord_UpdateButton = new JButton("Update");
        updatePatientRecord_UpdateButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        updatePatientRecord_UpdateButton.setBounds(30, 380, 72, 26);
        updatePatientRecord.add(updatePatientRecord_UpdateButton);
        updatePatientRecord_UpdateButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                updatePatientIDTextField_Data = updatePatientIDTextField.getText();
                updateNameTextField_Data = updateNameTextField.getText();
                updateContactNumberTextField_Data = updateContactNumberTextField.getText();
                updateAgeTextField_Data = updateAgeTextField.getText();
                if (updateGenderMaleRadioButton.isSelected()) {
                    updateGenderButtonGroup_Data = updateGenderMaleRadioButton.getText();
                } else if (updateGenderFemaleRadioButton.isSelected()) {
                    updateGenderButtonGroup_Data = updateGenderFemaleRadioButton.getText();
                } else if (updateGenderOtherRadioButton.isSelected()) {
                    updateGenderButtonGroup_Data = updateGenderOtherRadioButton.getText();
                }
                updateBloodGroupList_Data = (String) updateBloodGroupList.getSelectedItem();
                updateAddressTextArea_Data = updateAddressTextArea.getText();
                updateMajorDiseaseTextArea_Data = updateMajorDiseaseTextArea.getText();
                try {
                    Socket soc = new Socket("192.168.137.1", 1945);
                    BufferedReader in = new BufferedReader(new InputStreamReader(soc.getInputStream()));
                    PrintWriter out = new PrintWriter(soc.getOutputStream(), true);
                    out.println(updatePatientIDTextField_Data);
                    out.println(updateNameTextField_Data);
                    out.println(updateContactNumberTextField_Data);
                    out.println(updateAgeTextField_Data);
                    out.println(updateGenderButtonGroup_Data);
                    out.println(updateBloodGroupList_Data);
                    out.println(updateAddressTextArea_Data);
                    out.println(updateMajorDiseaseTextArea_Data);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }

                updatePatientIDTextField.setText("");
                updateNameTextField.setText("");
                updateContactNumberTextField.setText("");
                updateAgeTextField.setText("");
                updateGenderUnselectedRadioButton.setSelected(true);
                updateAddressTextArea.setText("");
                updateMajorDiseaseTextArea.setText("");
            }
        });

        updatePatientRecord_CloseButton = new JButton("Close");
        updatePatientRecord_CloseButton.setFont(new Font("Poppins", 0, 12)); // NOI18N
        updatePatientRecord_CloseButton.setBounds(380, 380, 72, 26);
        updatePatientRecord.add(updatePatientRecord_CloseButton);
        updatePatientRecord_CloseButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                dispose();
            }
        });
        tabbedPane.addTab("New Patient Record", null, newPatientRecordPanel, "New Patient Record");
        tabbedPane.addTab("Diagnosis Information", null, diagnosisInformationPanel, "Diagnosis Information");
        tabbedPane.addTab("History of Patient", null, historyOfPatientPanel, "History of Patient");
        tabbedPane.addTab("Update Patient Record", null, updatePatientRecord, "Update Patient Record");

        tabbedPane.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        patientDetailsPagePanel.add(tabbedPane);
        add(patientDetailsPagePanel);

        pack();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home lf = new Home();
                lf.setSize(560, 500);
                lf.setResizable(false);
                lf.setLocationRelativeTo(null);
                Image icon = Toolkit.getDefaultToolkit().getImage("logo.png");
                lf.setIconImage(icon);
                lf.setVisible(true);
            }
        });
    }
}